# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
chrome_options = Options()
chrome_options.add_argument("--headless")


class TestLogin():
    def setup_method(self):
        self.driver = webdriver.Chrome(options=chrome_options)
        self.vars = {}
    
    def teardown_method(self):
        self.driver.quit()
    
    def test_login(self):
        self.driver.get("http://localhost:1667/")
        self.driver.set_window_size(918, 824)
        self.driver.find_element(By.LINK_TEXT, "Sign in").click()
        self.driver.find_element(By.XPATH, "//input[@type=\'text\']").click()
        self.driver.find_element(By.XPATH, "//input[@type=\'text\']").send_keys("ntest2@ceg.hu")
        self.driver.find_element(By.XPATH, "//input[@type=\'password\']").send_keys("ntest222A")
        self.driver.find_element(By.XPATH, "//button[contains(.,\'Sign in\')]").click()
        time.sleep(2000)
        assert self.driver.find_element(By.LINK_TEXT, "ntest2").text == "ntest2"
        time.sleep(2000)
        self.driver.find_element(By.LINK_TEXT, "Log out").click()
